name: Node.js CI/CD with ZAP

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/node-app
            git pull origin main
            docker compose down || true
            docker compose up -d --build

  zap_scan:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://${{ secrets.EC2_HOST }}:8000"
          fail_action: false   # Don’t fail the pipeline on warnings
          cmd_options: "-a -l WARN"

      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_reports   # ✅ safe name
          path: |
            report_json.json
            report_md.md
            report_html.html

      - name: Upload ZAP Reports to S3
        uses: aws-actions/s3-sync@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          source: .
          destination: zap-reports
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
