name: OWASP ZAP Scan

on:
  workflow_dispatch: # or workflow_run after deploy

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline and Upload to S3
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ZAP_EC2_HOST }}
          username: ${{ secrets.ZAP_EC2_USER }}
          key: ${{ secrets.ZAP_EC2_SSH_KEY }}
          timeout: 30m
          script: |
            cd /home/ec2-user
            mkdir -p zap-reports
            docker run --rm -v /home/ec2-user/zap-reports:/zap/wrk/:rw \
              ghcr.io/zaproxy/zaproxy:weekly \
              zap-baseline.py \
              -t http://${{ secrets.APP_EC2_HOST }}:8000 \
              -J report.json \
              -r report.html \
              -w report.md \
              -a -l FAIL

            # Upload reports to S3 from inside EC2
            aws s3 cp /home/ec2-user/zap-reports/ s3://my-report-s3-buckett/zap-reports/ --recursive --region eu-north-1
